# Generated by Django 5.0.3 on 2024-04-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
