# Generated by Django 5.0.3 on 2024-03-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='qua',
            new_name='quantity',
        ),
    ]
