# Generated by Django 5.0.3 on 2024-03-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_desc_inventoryitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
