# Generated by Django 5.0.3 on 2024-03-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
