# Generated by Django 5.0.3 on 2024-03-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_itemid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='itemID',
        ),
    ]
