# Generated by Django 5.0.3 on 2024-04-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventoryitem_itemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
