# Generated by Django 5.0.4 on 2024-04-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryitem_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=100)),
                ('delivery_status', models.CharField(choices=[('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='In Transit', max_length=20)),
                ('payment_type', models.CharField(choices=[('COD', 'Cash on Delivery')], default='COD', max_length=10)),
            ],
        ),
    ]
