# Generated by Django 5.0.4 on 2024-04-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_scheduleddelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='vendor',
            field=models.CharField(choices=[('Boy Bondat', 'Boy Bondat'), ('Mang Boks', 'Mang Boks'), ('Potato King', 'Potato King'), ('Siomai King', 'Siomai King'), ('Siopao Da King', 'Siopao Da King')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
